---
- name: Demo playbook to deploy nginx
  hosts: all
  tasks:
    
    - name: Install nginx package
      apt:
        name: nginx
        state: latest
    
    - name: Start and enable apache2 service
      service:
        name: nginx
        enabled: true
        state: started

    - name: Create a custom index.html file
      copy:
        dest: /var/www/html/index.html
        content: |
          <h1>Welcome to DevOps Ansible Nginx server deployment</h1>
