---
- name: Demo playbook to test callback plugin - Deployment
  hosts: all
  tasks:
    
    - name: Install apache package
      apt:
        name: apache2
        state: latest
    
    - name: Start and enable apache2 service
      service:
        name: apache2
        enabled: true
        state: started

    - name: Create a custom index.html file
      copy:
        dest: /var/www/html/index.html
        content: |
          <h1>Welcome to DevOps Ansible</h1>
