---
- name: Demo playbook to Remove
  hosts: all
  tasks:

    - name: Stop and disable apache service
      service:
        name: apache2
        enabled: false
        state: stopped

    - name: Remove apache2 package
      apt:
        name: apache2
        state: absent
